### ISSUE TITLE
Different path for lxrun and bash

### ISSUE THREAD

**Issue by cbsirb** [RoliSoft/WSL-Distribution-Switcher#1]
Hi, on my system lxrun and bash are not in c:\windows\sysnative but in c:\windows\system32

I fixed the scripts by removing the c:\windows\sysnative and allow the scripts to run the the lxrun and bash from PATH, but that may conflict with users using cygwin/msys2.

An option to select the path for lxrun/bash should be provided or to verify the executables before.

Thanks!

**Comment by RoliSoft** [comment]
Hi,

I've added some code in ec96230 to detect whether `lxrun.exe` is in `sysnative` or `system32`.

Running from `%PATH%` or `system32` doesn't seem to work for me from inside of Python, I just get the following error:

```
'bash.exe' is not recognized as an internal or external command,
operable program or batch file.
```

Please try to see if the new code works for you. If not, please tell me which build of Windows 10 are you using, so I can try replicating it in a VM. I'm on the non-insider anniversary update, for future reference.

**Comment by cbsirb** [comment]
I'm running the RS1 (build 14393), but the windows itself was updated form 8.1 -> 10 -> 10 TH2 -> 10 RS1 so maybe that's why it stayed in **system32** and why I don't have the **sysnative** folder.

I will try the new build when I have some free time.

EDIT: Just changed from fedora to debian. It works now. Thanks a lot!
