### ISSUE TITLE
Failed to fetch manifest info for distro: HTTP Error 404: NOT FOUND

### ISSUE THREAD

**Issue by robeastham** [RoliSoft/WSL-Distribution-Switcher#11]
Not sure why but I seem to be getting errors for any of the tagged official distros, but not 3rd party. Anyone have any ideas why this might be?

```

C:\Users\USER\Code\WSL-Distribution-Switcher>python get-prebuilt.py alpine:latest
[*] Requesting authorization token...
[*] Fetching manifest info for alpine:latest...
[!] Failed to fetch manifest info for alpine: HTTP Error 404: NOT FOUND

C:\Users\USER\Code\WSL-Distribution-Switcher>python get-prebuilt.py ubuntu:trusty
[*] Requesting authorization token...
[*] Fetching manifest info for ubuntu:trusty...
[!] Failed to fetch manifest info for ubuntu: HTTP Error 404: NOT FOUND

C:\Users\USER\Code\WSL-Distribution-Switcher>python get-prebuilt.py pritunl/archlinux
[*] Requesting authorization token...
[*] Fetching manifest info for pritunl/archlinux:latest...
[*] Downloading layer sha256:fa15d8aec9382c4924fd3ec2f716d6d7733acdcb5ce2dff508e0a783dbe2d469...
```

**Comment by RoliSoft** [comment]
f360e84 fixes this. It seems I need to prefix the name with `library/` when asking for the official images.

(PS: Alpine won't run, you'll just get `Error: 0x80070002`. I wasn't able to get any busybox-based distro running, although I haven't really had the time to track down why they are failing.)

**Comment by robeastham** [comment]
Actually, I also got `Error: 0x80070002` after typing in `bash`  last time I tried to install Alpine. I think I ended up having to reinstall WSL to get rid of it. Shame as I'm keen to try and use Alpine wherever I can. Guess I'll stick with Arch for now.

Good to know some of the official images are now available again if I need them. Thanks for fixing the bug so quickly.
