### ISSUE TITLE
Installation using Cygwin's Python is broken

### ISSUE THREAD

**Issue by grebenyukaa** [RoliSoft/WSL-Distribution-Switcher#13]
Hi guys.
I am trying to install debian:latest from cygwin console, but keep getting the error:

> $ python3 install.py debian:latest
> [*] Probing the Linux subsystem...
> Traceback (most recent call last):
>   File "install.py", line 34, in <module>
>     basedir, lxpath = probe_wsl()
>   File "/cygdrive/c/Users/amadeus/Desktop/tmp/WSL-Distribution-Switcher/utils.py", line 125, in probe_wsl
>     basedir = os.path.join(os.getenv('LocalAppData'), 'lxss')
>   File "/usr/lib/python3.4/posixpath.py", line 82, in join
>     path += b
> TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

Steps to reproduce:

> python3 get-prebuilt.py debian:latest
> python3 install.py debian:latest

My python version is:

> $ python3 --version
> Python 3.4.3

Same thing happens for python2(2.7.10), but with a slightly different error:

> $ python install.py debian:latest
> [*] Probing the Linux subsystem...
> Traceback (most recent call last):
>   File "install.py", line 34, in <module>
>     basedir, lxpath = probe_wsl()
>   File "/cygdrive/c/Users/amadeus/Desktop/tmp/WSL-Distribution-Switcher/utils.py", line 125, in probe_wsl
>     basedir = os.path.join(os.getenv('LocalAppData'), 'lxss')
>   File "/usr/lib/python2.7/posixpath.py", line 70, in join
>     elif path == '' or path.endswith('/'):
> AttributeError: 'NoneType' object has no attribute 'endswith'

WSL is enabled, lxrun /? shows the help text.

Thanks in advance!

**Comment by RoliSoft** [comment]
Hi,

It seems I forgot that Python under Cygwin uses /cygdrive/ for paths, not the Windows version.

I will need to check for this and handle the paths accordingly.

In the meantime, you won't be able to do anything with the scripts under Cygwin. If you're eager, you could try the official Windows version of Python 3.

**Comment by RoliSoft** [comment]
Seems like this has more challenges than just the correct path handling. A few crucial Windows-specific calls are missing from Cygwin's Python that are otherwise present in the Windows distribution. For example, `ctypes.windll` for `__stdcall`-ing the ntfsea library functions is missing, only `ctypes.cdll` is present with the `__cdecl` calling convention. Other than that, simple things such as `sys.getwindowsversion()` or `os.getenv('LocalAppData')` are missing, or don't return the expected value.

**Comment by Efreak** [comment]
There is no `winreg` package in cygwin's\* python. There is a cygwinreg available for installing via pip, however installing it doesn't help, even if I swap [utils.py:8](https://github.com/RoliSoft/WSL-Distribution-Switcher/blob/master/utils.py#L8) to `import cygwinreg`.

It should be fairly simple to get around some of the mentioned issues; 
- ~~sys.getwindowsversion()~~
  - `cmd.exe /c ver`
  - `systeminfo.exe | grep OS`
  - python: `platform.system()`
- ~~`os.getenv('LocalAppData')`~~
  - `cmd.exe /c echo %LocalAppData%`
  - python: `os.getenv('LOCALAPPDATA')`
- ~~`import winreg`~~
  - /proc/registry (read-only)
  - `regedit.exe file.reg` (requires a .reg file)
  - `reg.exe query /?`, `reg.exe add /?`, `reg flags /?`

\* I'm actually using [babun](http://babun.github.io/), but it uses uses the same setup.ini to download the same binaries as setup.exe.

**Comment by RoliSoft** [comment]
Thank you for taking the time and contributing solutions. I've made some progress over the weekend, but didn't have time to finish it yet.

For future reference, there are a few better solutions, such as fallback to `cygwinreg`:

```
try:
    import _winreg
except:
    import cygwinreg
```

And as for handling paths and expanding such variables, `cygpath` is a really useful command that comes preinstalled with Cygwin.

I'm not using babun, however, as far as I know it is based on Cygwin and should not deviate so hard that the script would not. Should babun not work when the Cygwin support comes out, please open a separate ticket, so I can take a look at it.

I'm trying to support most scenarios Windows users could be running a Python script under.

**Comment by RoliSoft** [comment]
Well, cygwinreg does not support Python 3, so that solution is completely out.

Otherwise all other issues are fixed, and the script _would be_ ready to go.

**Comment by RoliSoft** [comment]
1036f15 adds support for Cygwin, _however_, it does not work yet.

Cygwin has a weird permission mapping scheme[[1]](https://cygwin.com/ml/cygwin/2010-05/msg00393.html)[[2]](https://cygwin.com/cygwin-ug-net/ntsec.html#ntsec-mapping), which requires permissions to be completely reset before Windows can access any files or directories created.

Although running `icacls rootfs-temp /t /reset` fixes this after the fact, while the extraction is happening, the NTFS Extended Attributes writer library has no access to the files, and as such the extracted files have no extended attributes.

This is a pretty annoying issue, it would be really nice if I could temporarily turn off this Windows-breaking permission mapping scheme. Alternatively, I'll most likely delay the attribute restoration part, however, this requires significant design changes on my part.

**Comment by RoliSoft** [comment]
1036f15 fixes the permission issue.

One more issue left: on WSL versions before Windows interoperability, the hook scripts won't run as the output cannot be piped into Mintty. The user will just get "  r r o r :   0 x 8 0 0 7 0 0 5 7".

Otherwise, the WSL installation is working. On Insider previews, the hook scripts will work as well.
