### ISSUE TITLE
pritunl/archlinux still failing the post-install hook part if you don't delete the pycache

### ISSUE THREAD

**Issue by fpqc** [RoliSoft/WSL-Distribution-Switcher#18]
Hi there Rolisoft,

I tried doing the steps, get-prebuilt, then install, and if I didn't delete the pycache file, the build process for pacaur would fail because it would say it couldn't find awk.

Also, there's a small error when it tries to extract the apache license.txt file at the very beginning of the install, but it doesn't seem to matter.

**Comment by RoliSoft** [comment]
Hi,

I'm not sure I understand the issue here. After you delete the pycache file, everything is working alright?

Besides the apache license.txt file, not sure on that one, didn't seem like a high priority issue to investigate, but I'll look into it when I have the time.

**Comment by fpqc** [comment]
@rolisoft After deleting pycache, it did install, but `awk` (package gawk on arch) was either not installed or corrupted. It did work after I manually reinstalled gawk with pacman. (`awk` is a dep of pacaur).

**Comment by RoliSoft** [comment]
Not sure if it's from the new installer, or gawk is just corrupted in this particular archive.

83c137a updates the script to reinstall gawk, just in case.

**Comment by fpqc** [comment]
Cool =]
