### ISSUE TITLE
debian doesn't install sudo

### ISSUE THREAD

**Issue by roryst** [RoliSoft/WSL-Distribution-Switcher#21]
i just installed debian, but sudo didn't get installed. i set the regular username/password, but how do i su into root to install sudo? thanks

**Comment by RoliSoft** [comment]
The base debian package from the Docker hub does not contain the sudo package.

If you don't have sudo or you lock yourself out, you can gain root, by running the following in the command prompt (not bash):

    lxrun /setdefaultuser root

This will set the default user to root. Running bash will now drop you into a root shell, and you can install the sudo package. To switch back to your original user, just re-run the command and replace "root" with your username in WSL.

_Note:_ The script comes with some post-install hooks, which install sudo amongst other things, and a few fixes for known issues. To enable running the hooks after installation, rename the `hook_postinstall_all.sample.sh` file to `hook_postinstall_all.sh`, and `install.py` will now invoke this script on subsequent installations.
