### ISSUE TITLE
Couldn't get root access in Fedora

### ISSUE THREAD

**Issue by raad-orfali** [RoliSoft/WSL-Distribution-Switcher#29]
I used the script to install fedora and enabled the hook script but still can not get access to the root account neither can install sudo
note: I already put ROOTPASSWD in system environment variables - System Variables

also how can I delete installed image as I tried to re install fedora after removing the sample from the hook file and now the switch script show I have two copies of fedora:latest

**Comment by RoliSoft** [comment]
You can run "lxrun /setdefaultuser root" from command prompt (not inside WSL) to set the default user as root. Then, running bash would drop you into a root shell, where you can change the password with "passwd" and install sudo with "dnf install sudo".

That being said, this should not have happened if you ran the hook script. Did the script run, or did it fail with an error message at one point?

For future reference, though, the "distributions" are stored in `C:\Users\<username>\AppData\Local\lxss`. There, you'll see a `rootfs` folder, this is your current active one. You'll also see `rootfs_ubuntu_trusty`, this is the old rootfs that came with Windows. Rename or remove `rootfs`, and rename `rootfs_ubuntu_trusty` back to `rootfs`, to get your original shell back. (Note: make sure no WSL instances are running while you are doing this.)

**Comment by gbraad** [comment]
@RoliSoft installing `dnf install sudo` will core dump... => #32

**Comment by RoliSoft** [comment]
Closing this issue. The segmentation fault will now be tracked in #22, since it is the first issue reporting this.
