### ISSUE TITLE
Failed to run hook in WSL when using Fedora:latest

### ISSUE THREAD

**Issue by ikky888** [RoliSoft/WSL-Distribution-Switcher#31]
Is this a know issue? I am not finding anyone who documented such issue:

[*] Installing tools...
error: rpmdb: BDB0113 Thread/process 7/140163040478976 failed: BDB1507 Thread died in Berkeley DB library
error: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: cannot open Packages index using db5 -  (-30973)
error: cannot open Packages database in /var/lib/rpm
Error: Error: rpmdb open failed
[!] Failed to run hook in WSL: Command '['cmd', '/C', 'C:\\windows\\System32\\bash.exe', '-c', 'REGULARUSER="ikky" WINVER="14393" /root/hook_postinstall_all.sh']' returned non-zero exit status 1.
[*] Switching default user back to ikky...

**Comment by RoliSoft** [comment]
Closing this issue. The segmentation fault will now be tracked in #22, since it is the first issue reporting this.
