### ISSUE TITLE
Core dumped on fedora:25, dnf install -y sudo

### ISSUE THREAD

**Issue by gbraad** [RoliSoft/WSL-Distribution-Switcher#32]
*Steps to reproduce:*
```
C:/> python install.py fedora:25
C:/> lxrun /setdefaultuser root
C:/> bash
$ dnf install -y sudo
```
During the install a `Segmentation fault (Code dumped)` occurs and the RPM db is corrupted.

The image `fedora:24` works as expected:
```
C:/> python install.py fedora:24
C:/> lxrun /setdefaultuser root
C:/> bash
$ dnf install -y sudo
```
Installs and finishes.

**Comment by gbraad** [comment]
duplicate of #22

**Comment by RoliSoft** [comment]
Closing this issue. The segmentation fault will now be tracked in #22, since it is the first issue reporting this.
