### ISSUE TITLE
kali linux docker image returns 401 with get-prebuild.py: unauthorized

### ISSUE THREAD

**Issue by Simbaclaws** [RoliSoft/WSL-Distribution-Switcher#33]
for some reason when I try to download the docker image for kali it downloads through about 6 layers, but the last layer tells me http error 401: unauthorized.

Could I perhaps use a different tool to download the image to see if the problem persists? I'm a bit of a docker newb.

EDIT: I've tried doing it with docker pull and docker save but this saves layers in a tar.gz instead of the actual rootfs.

EDIT2: Do I simply combine the layers into a single .tar.gz? How would I go about doing this? I have the docker image but it contains layers...

**Comment by Simbaclaws** [comment]
Apparently I could download the image with docker pull instead of get-prebuild.py

After the install.py I'm getting lots of error messages, sudo not being installed, switching to root gives me errors like: error while loading shared libraries libcap-ng.so.0: cannot open shared object file: No such file or directory.

To me it seems like the base install went wrong somehow.

**Comment by RoliSoft** [comment]
First of all, which image are you trying to pull? The official is `kalilinux/kali-linux-docker`. It has 14 layers right now, and it downloads without any issues for me.

Could you check if it is working for you right now as well? Could have been a temporary issue with the docker registry API.

Also, for future reference, yes, you can just concatenate all the layers into a single file. However, the same can be achieved by using `docker export`: the output will be a single tar file.

**Comment by IcyCC** [comment]
i meet the same problem,how you fix it?

**Comment by opus-x** [comment]
Same problem here.

```
> python get-prebuilt.py kalilinux/kali-linux-docker
[*] Requesting authorization token...
[*] Fetching manifest info for kalilinux/kali-linux-docker:latest...
[!] Failed to fetch manifest info for kalilinux/kali-linux-docker: HTTP Error 401: Unauthorized
```

**Comment by imranalamhadi** [comment]
Same Issue

admin321@DESKTOP-GVDVIHK:~/WSL-Distribution-Switcher$ python3 get-prebuilt.py kalilinux/kali-linux-docker
[*] Requesting authorization token...
[*] Fetching manifest info for kalilinux/kali-linux-docker:latest...
[!] Failed to fetch manifest info for kalilinux/kali-linux-docker: HTTP Error 401: Unauthorized

**Comment by null-nofile-404** [comment]
When I use the update command, I get a 401 error. What should I do?



Error: The repository 'http://repo.kali.org/kali kali-bleeding-edge InRelease' is not signed.
Notice: Updating from such a repository can't be done securely, and is therefore disabled by default.
Notice: See apt-secure(8) manpage for repository creation and user configuration details.
Error: Failed to fetch http://http.kali.org/kali/dists/kali-dev/InRelease  403  Forbidden [IP: 104.17.253.239 80]
Error: The repository 'http://http.kali.org/kali kali-dev InRelease' is not signed.
Notice: Updating from such a repository can't be done securely, and is therefore disabled by default.
Notice: See apt-secure(8) manpage for repository creation and user configuration details.
Error: The repository 'http://http.kali.org /kali Release' does not have a Release file.
Notice: Updating from such a repository can't be done securely, and is therefore disabled by default.
Notice: See apt-secure(8) manpage for repository creation and user configuration details.
Error: The repository 'http://http.kali.org /wheezy Release' does not have a Release file.
Notice: Updating from such a repository can't be done securely, and is therefore disabled by default.
Notice: See apt-secure(8) manpage for repository creation and user configuration details.
Error: The repository 'http://http.kali.org/kali kali Release' does not have a Release file.
Notice: Updating from such a repository can't be done securely, and is therefore disabled by default.
Notice: See apt-secure(8) manpage for repository creation and user configuration details.
Warning: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:9 and /etc/apt/sources.list:18
Warning: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:9 and /etc/apt/sources.list:18
Warning: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:9 and /etc/apt/sources.list:18
Warning: Target Contents-deb (main/Contents-amd64) is configured multiple times in /etc/apt/sources.list:9 and /etc/apt/sources.list:18
Warning: Target Contents-deb (main/Contents-all) is configured multiple times in /etc/apt/sources.list:9 and /etc/apt/sources.list:18
Warning: Target Packages (contrib/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:9 and /etc/apt/sources.list:18
Warning: Target Packages (contrib/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:9 and /etc/apt/sources.list:18
Warning: Target Translations (contrib/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:9 and /etc/apt/sources.list:18
Warning: Target Contents-deb (contrib/Contents-amd64) is configured multiple times in /etc/apt/sources.list:9 and /etc/apt/sources.list:18
Warning: Target Contents-deb (contrib/Contents-all) is configured multiple times in /etc/apt/sources.list:9 and /etc/apt/sources.list:18
Warning: Target Packages (non-free/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:9 and /etc/apt/sources.list:18
Warning: Target Packages (non-free/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:9 and /etc/apt/sources.list:18
Warning: Target Translations (non-free/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:9 and /etc/apt/sources.list:18
Warning: Target Contents-deb (non-free/Contents-amd64) is configured multiple times in /etc/apt/sources.list:9 and /etc/apt/sources.list:18
Warning: Target Contents-deb (non-free/Contents-all) is configured multiple times in /etc/apt/sources.list:9 and /etc/apt/sources.list:18
Notice: Repository 'Kali Linux' changed its 'firmware component' value from 'non-free' to 'non-free-firmware'
Notice: More information about this can be found online at: https://www.kali.org/blog/non-free-firmware-transition/
