### ISSUE TITLE
Can't install ubuntu xenial

### ISSUE THREAD

**Issue by ikky888** [RoliSoft/WSL-Distribution-Switcher#34]
I am hitting this after a fresh re-install of WSL and have Ubuntu:trusty installed:
>python get-source.py ubuntu:xenial
[*] Fetching official-images info for ubuntu:xenial...
[*] Fetching Dockerfile from repo tianon/docker-brew-ubuntu-core/1a5cb40f41ac4829d8c301ccd2cf3b7a13687a8b/xenial...
[*] Downloading archive https://raw.githubusercontent.com/tianon/docker-brew-ubuntu-core/1a5cb40f41ac4829d8c301ccd2cf3b7a13687a8b/xenial/ubuntu-xenial-core-cloudimg-amd64-root.tar.gz...
[*] Rootfs archive for ubuntu:xenial saved to rootfs_ubuntu_xenial.tar.gz.

>python get-prebuilt.py ubuntu:xenial
[*] Requesting authorization token...
[*] Fetching manifest info for ubuntu:xenial...
[*] Downloading layer sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4...
[*] Downloading layer sha256:6d9ef359eaaa311860550b478790123c4b22a2eaede8f8f46691b0b4433c08cf...
[*] Downloading layer sha256:9654c40e9079e3d5b271ec71f6d83f8ce80cfa6f09d9737fc6bfd4d2456fed3f...
[*] Downloading layer sha256:e8db7bf7c39fab6fec91b1b61e3914f21e60233c9823dd57c60bc360191aaf0d...
[*] Downloading layer sha256:f8b845f45a87dc7c095b15f3d9661e640ebc86f42cd8e8ab36674846472027f7...
[*] Downloading layer sha256:d54efb8db41d4ac23d29469940ec92da94c9a6c2d9e26ec060bebad1d1b0e48d...
[*] Rootfs archive for ubuntu:xenial saved to rootfs_ubuntu_xenial.tar.gz.

>python install.py ubuntu:xenial
[*] Probing the Linux subsystem...
[*] Default user is ikky at /home/ikky.
[*] Reading /etc/{passwd,shadow,group,gshadow} entries for root and ikky...
[*] Beginning extraction...
[!] Failed to extract archive: [WinError 126] The specified module could not be found

P.S: WSL was NOT running when I was executing these commands.

**Comment by RoliSoft** [comment]
I'm not entirely sure which one you ended up installing. Please use either `get-source` or `get-prebuilt` but not both, because then you'll get two. If the issue still persists, please reopen the ticket, so I can investigate further.
