### ISSUE TITLE
No sudo after installing Debian Stretch and root password unknown

### ISSUE THREAD

**Issue by RikuKawai** [RoliSoft/WSL-Distribution-Switcher#35]
I successfully switched to Debian Stretch, but sudo does not come installed by default and I cannot obtain root access to install it.

**Comment by ikky888** [comment]
This is "literally" the first issue listed under Code tab in the Troubleshooting section:
<quote>
Troubleshooting

    no root rights / no sudo / su -l fails with Authentication failure

The script migrates both your regular user and root's password, however, for some reason I found it to be not working perfectly with all distributions in case of root.

In any case, to fix this, you can switch the default user to root on WSL and then reset the root password with with:

> lxrun /setdefaultuser root
> bash
$ passwd

Logging in with su -l as root should work now. If passwd is not available, you can install it with the package manager of the distribution. Same goes with sudo, just make sure to edit the sudoers with visudo to empower your regular account. 
</quote>

Did you try that?

**Comment by RikuKawai** [comment]
My bad, I didn't see that. Yes that worked, thanks.
