### ISSUE TITLE
Unable to run get-sources

### ISSUE THREAD

**Issue by c-stauffer** [RoliSoft/WSL-Distribution-Switcher#43]
Can't even start the thing. Output below. I don't know what other info I can provide.

```
c:\Users\Chris\Downloads>python get-source.py opensuse:tumbleweed
Traceback (most recent call last):
  File "get-source.py", line 10, in <module>
    ensure_ca_load()
  File "c:\Users\Chris\Downloads\utils.py", line 85, in ensure_ca_load
    if ssl.create_default_context().cert_store_stats()['x509_ca'] == 0:
AttributeError: 'module' object has no attribute 'create_default_context'

c:\Users\Chris\Downloads>python --version
Python 3.3.5
```

**Comment by RoliSoft** [comment]
`ssl.create_default_context` was added in Python 3.4. As it would not be a trivial fix to add this, I'm closing this ticket. Please update your installation.

Alternatively, you could just remove the calls to `ensure_ca_load()`, as they are just helper functions to load certifi, if the Windows CA list has not loaded.
