### ISSUE TITLE
New error 0x80070040 w/WSL after using Switcher, Win build 16241

### ISSUE THREAD

**Issue by xunlinkx** [RoliSoft/WSL-Distribution-Switcher#53]
Experiencing this on 10.0.16241 Build 16241 Home, Insider Fast Ring
Everything was working fine until the latest build came down for me. I previously was using Fedora 25. The first time I experienced this I did an lxinstall /uninstall /y /full - and uninstalled WSL in Windows features, then reinstalled.
```
C:\Users\tronik>lxrun /install
Warning: lxrun.exe is only used to configure the legacy Windows Subsystem for Linux distribution.
Distributions can be installed by visiting the Windows Store:
https://aka.ms/wslstore

-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: tronik
Enter new UNIX password:
Retype new UNIX password:
passwd: password updated successfully
Installation successful!
Documentation is available at:  https://aka.ms/wsldocs
```
I then run bash, passwd for tronik, sudo passwd root, to change passwords.

And then... get-prebuilt.py for fedora:latest and 
```
C:\opt\WSL-Distribution-Switcher>install.py fedora:latest
[*] Probing the Linux subsystem...
[*] Default user is tronik at /home/tronik.
[*] Reading /etc/{passwd,shadow,group,gshadow} entries for root and tronik...
[*] Removing leftover rootfs-temp...
[*] Beginning extraction...
[*] Backing up current rootfs to rootfs_ubuntu_xenial...
[*] Switching to new rootfs...
[*] Writing entries of root and tronik to /etc/{passwd,shadow,group,gshadow}...

C:\opt\WSL-Distribution-Switcher>switch.py
usage: ./switch.py image[:tag]

The following distributions are currently installed:

  - fedora:latest*
  - ubuntu:xenial

You do not seem to have the default distribution installed anymore.
To reinstall it, run lxrun /uninstall and lxrun /install from the command prompt.

C:\opt\WSL-Distribution-Switcher>bash
Error: 0x80070040
Press any key to continue...
```

In addition, restarting or stopping/starting lxssmanager has no effect.
As well as trying to switch back to ubuntu:xenial with switch.py yields message about Linux subsystem is currently running. Please kill all instances before continuing.

**Comment by xunlinkx** [comment]
Issue was remedied after downloading via get-source.py instead of get-prebuilt.

**Comment by Calinou** [comment]
**OS:** Windows 10 Creators Update (build 15063)
**Python version:** 3.5.3

After clearing my previous WSL and installing a fresh default WSL (Ubuntu 16.04, using the official utility), I attempted to install Fedora 26 (tried using both `get-prebuilt.py` and `get-source.py`), but I also get an `0x80070040` error when starting `bash` (although `install.py` runs without any errors – also, the official WSL didn't have that error).

**Comment by jhasse** [comment]
It's the same for me with build 15063.

**Comment by undefined1** [comment]
C:\Users\ZODtheIMORTAL1\Desktop\WSL\WSL-Distribution-Switcher>python install.py rootfs_kalilinux_kali-linux-docker_latest.tar.gz
[*] Probing the Linux subsystem...
[!] The Linux subsystem is currently running. Please kill all instances before continuing.

C:\Users\ZODtheIMORTAL1\Desktop\WSL\WSL-Distribution-Switcher>

I'm so lost.. i've had this problem for days and nothing suggested has worked please help
