### ISSUE TITLE
Alpine Linux

### ISSUE THREAD

**Issue by zippaaa** [RoliSoft/WSL-Distribution-Switcher#56]
Excuse me, did anyone install Alpine Linux?
python install.py alpine:latest
... OK ...
But, Bash cant't run.

**Comment by RoliSoft** [comment]
Alpine Linux uses musl libc, which is not compatible with WSL for some reason. This is a WSL issue, but since none of the officially supported distributions use musl libc, I'm not sure if Microsoft will look at it.

Progress is being kept in another issue on this.

**Comment by zippaaa** [comment]
https://github.com/Microsoft/BashOnWindows/issues/2372
