### ISSUE TITLE
declares Linux subsystem not installed - Fall Creators Update

### ISSUE THREAD

**Issue by ghost** [RoliSoft/WSL-Distribution-Switcher#64]
```
C:\Users\tao\Documents\GitHub\WSL-Distribution-Switcher> python.exe .\install.py .\rootfs_clearlinux_latest.tar.gz
[*] Probing the Linux subsystem...
[!] The Linux subsystem is not installed. Please go through the standard installation procedure first.
```

**Comment by wizsilex** [comment]
I also have this problem :(

**Comment by briancamp** [comment]
Me too.

Its happening on a laptop that I installed with a fresh copy of Fall Creators / 1709. Its not happening though on a machine that I installed WSL on and then updated to 1709.

**Comment by ghost** [comment]
unfortunately this is happening on a machine i installed WSL on and then updated to 1709.

**Comment by wizsilex** [comment]
Im not sure, but I think i solved this by running
`LxRun.exe /install`

**Comment by briancamp** [comment]
For me, running `LxRun.exe /install` allowed `install.py` to to run through its installation without error, but launching bash still goes into Ubuntu rather than the distribution I installed (Centos).

**Comment by christian-korneck** [comment]
> python.exe .\install.py debian:sid
>[!] The Linux subsystem is not installed. Please go through the standard installation procedure

I had the same issue with `Win10-1709` ("Fall Creators Update"). This workaround did it for me:

- install the legacy WSL Ubuntu distro:
  `lxrun.exe /install`
   - Explanation: this installs the `legacy` WSL Ubuntu distro known from older Windows10 versions (Win10-1703). Win10-1709 now supports multiple distros from the Store installed in parallel. The `legacy` distro is not the same as the `ubuntu` distro from the Store and can get installed in parallel:
    ```
    >wslconfig /list /all
    Windows Subsystem for Linux Distributions:
    Legacy (Default)
    Ubuntu
    ```
- make sure the `legacy` distro is the default one: `wslconfig /s legacy`
- set default user for the `legacy` distro to `root`: `lxrun /setdefaultuser root`
- delete/rename folder: `%localappdata%\lxss\temp`
- use `WSL-Distribution-Switcher` as usual, i.e. run something like: `python3 install.py debian:sid`

I actually like the fact that I can now have the unmodified, "reliable" `ubuntu` distro from the Store and in parallel have the `legacy` distro for experimental Linux setups via the switcher. (But an official interface/packager from Microsoft to build your own Distros would, of course, be much nicer. Until then, thanks a lot for the great switcher tools here!!). :-)

**Comment by aaroneg** [comment]
The actual code throwing this error is in utils.py, in the vicinity of line 185. Unfortunately I'm not a python person so I don't know what to do to fix it 🤷‍♂️

**Comment by iamrecursion** [comment]
The problem is that it is looking for the presence of the old `lxss` folder that is no longer installed by the store distributions. The store distributions are all downloaded to `%LOCALAPPDATA%\Packages\Canonical...` instead.

**Comment by elahia** [comment]
I run
` LxRun.exe /install `

and then this error occurred: 

`Failed to extract archive: [WinError 126] The specified module could not be found `   

any suggestion please?

**Comment by 0Serenvale** [comment]
I got permission problem any idea:

[*] Probing the Linux subsystem...
[*] Default user is ashisha at /home/ashisha.
[*] Reading /etc/{passwd,shadow,group,gshadow} entries for root and ashisha...
[*] Beginning extraction...
[*] Backing up current rootfs to rootfs_centos_latest...
[*] Switching to new rootfs...
[*] Writing entries of root and ashisha to /etc/{passwd,shadow,group,gshadow}...
[*] Switching default user to root...
[*] Running post-install hook all...
/bin/bash: /root/hook_postinstall_all.sh: Permission denied
[!] Failed to run hook in WSL: Command '['cmd', '/C', 'C:\\WINDOWS\\System32\\bash.exe', '-c', 'echo -n > /root/hook_postinstall_all.sh && chmod +x /root/hook_postinstall_all.sh']' returned non-zero exit status 1.
[*] Switching default user back to ashisha...

**Comment by eshack94** [comment]
This worked for me. Thank you kind sir!

Edit: Removed extraneous quoted text.

**Comment by cmeza** [comment]
MARTHA FOCKER! I cannot catch a break. This looks promising until I couldn't run/find `lxrun.exe` & then I found this:
https://docs.microsoft.com/en-us/windows/wsl/reference

`lxrun.exe is deprecated as of Windows 10 1803 and later.`

Any one else have another idea?

**Comment by christian-korneck** [comment]
> another idea

Most of the functionality of this tool is now available directly in WSL. In Windows Insiders Preview 18836 and 18841 it’s now possible to do distro imports/exports directly with wsl.exe.

And you can create your own distro app with https://github.com/Microsoft/WSL-DistroLauncher and Visual Studio.

**Comment by lquenti** [comment]
Sorry for Necrobumping but besides everything written here nothing worked.

For me, to get the named Debian folder, I had to explicitly install Debian from the Windows store. Hope that helps some of you as well

**Comment by yochenhsieh** [comment]
Sorry, is it possible to adapt the codes to compatible with 1809 or later? I want to install a distro that's not in Microsoft store.

**Comment by YanmhHP** [comment]
![image](https://user-images.githubusercontent.com/22751903/62700277-166f0e80-ba14-11e9-98f5-7ebc242afb18.png)
I also have this problem，and not sure if it's caused by the problem above,。Hopefully someone can answer it. Thanks!

**Comment by AngelTs** [comment]
Not work on 1809. At least set that notification in the mail page- so much time waste because of it!!!!

**Comment by sarawgeek** [comment]
if you are trying to install package like Kali, then this switcher is hardcoded to look for debian package only, so you can go and change
->go to %LocalAppData% in Run window
-> Copy the folder name of your package, in my case it was "KaliLinux.54290C8133FEE_ey8k8hqnwqnmg"
-> go inside WSL-Distribution-Switcher folder and open utils.py
-> go to function probe_wsl(silent=false)
-> change the packagesSubFolder
Now try.
you might get some debian.exe related error, in that case, do this after above steps
-> go to install.py
-> find this call -> get_lxss_user()
-> remove this call and assign values like this
uid=0
gid=0
user='root'

**Comment by diegomejia** [comment]
Everything @sarawgeek said was true for me too. I just had to do one extra minor step because I'm on a version of Windows 10 that has the lxrun.exe application deprecated so it wasn't available to me. I was getting this error:

Unable to find lxrun.exe in the expected locations.

The fix was simple, replace the call to lxrun.exe with 'wsl.exe' in util.py at line 219 so it looks like this:

	for path in lxpaths:
		if os.path.exists(os.path.join(path, 'wsl.exe')):
			lxpath = path
			break

That, in combination with the other tips @sarawgeek mentioned, got the install working for me.

**Comment by rpili1313** [comment]
The only thing you need to do is go to the windows store and install the Debian package from there.
