### ISSUE TITLE
win10 1709 version cannot use this script

### ISSUE THREAD

**Issue by alayamanas** [RoliSoft/WSL-Distribution-Switcher#68]
WSL changed the installation directory in win10 1709 version.
so install.py says:
[!] The Linux subsystem is not installed. Please go through the standard installation procedure first.

**Comment by shyim** [comment]
I have solved the issue by downloading the ubuntu app from windows store

**Comment by gauravhub** [comment]
Looks like the location of Lxss folder has been changed post Fall Creators Update. https://github.com/Microsoft/WSL/issues/2578
