### ISSUE TITLE
Any way to share files between distributions outside of home?

### ISSUE THREAD

**Issue by SRGOM** [RoliSoft/WSL-Distribution-Switcher#8]
I want to share my java distribution (currently in /opt) between distributions. Is there a recommended way to share it? The way I see it, only home directory stays outside rootfs.

Only asking, not requesting a feature.

Thank you, Great work btw!

**Comment by thebitstick** [comment]
You could put a folder named `opt` in your home folder and then symlink it to `/opt`.
Then just make the symlink whenever you install a new distro.
Switching between distros should keep the symlink.

**Comment by SRGOM** [comment]
Thanks, I think this should do...

**Comment by RoliSoft** [comment]
@SRGOM Pretty much what @thebitstick said. You could add the `ln` line to your hook script.

**Comment by thebitstick** [comment]
`sudo ln -s opt /opt && sudo chmod 755 /opt`

**Comment by thebitstick** [comment]
Also @SRGOM, how did you get Java to work in WSL? Doesn't work for me.

**Comment by SRGOM** [comment]
@thebitstick I haven't. I was excited for a very brief  bit when I learnt of the "-Xint" option that allows it to work partially (still broken for actual use because of internal path issues but the hanging issue doesn't occur). However, it was too slow to be of any use on my projects.
