### ISSUE TITLE
Can't install CentOS 6

### ISSUE THREAD

**Issue by jdmansour** [RoliSoft/WSL-Distribution-Switcher#9]
I'm trying to install CentOS 6. Fetching the filesystem works, but I get an error message during installation (see below). It is the same error message that you got [here](https://lab.rolisoft.net/blog/switching-the-distribution-behind-the-windows-subsystem-for-linux.html) under "Installing the new rootfs".

If I try to start WSL with `bash.exe` afterwards, nothing happens. No error message, it just returns me to the prompt.

The issue seems to be that the old CentOS version's `adduser` doesn't take the `--quiet` parameter, and that trips up `lxrun.exe`. However `/etc/passwd` and `/etc/shadow` seem to be edited correctly. Any ideas how to get this running?

```
> python get-source.py centos:6
> python install.py centos:6
[*] Probing the Linux subsystem...
[*] Default user is jason at /home/jason.
[*] Switching default user to root...
[*] Reading /etc/{passwd,shadow,group,gshadow} entries for root and jason...
[*] Copying rootfs_centos_6.tar.xz to /root/rootfs-temp...
[*] Beginning extraction...
[*] Waiting for the Linux subsystem to exit...
[*] Backing up current rootfs to rootfs_ubuntu_trusty...
[*] Switching to new rootfs...
[*] Writing entries of root and jason to /etc/{passwd,shadow,group,gshadow}...
[*] Switching default user back to jason...
/usr/sbin/adduser: unrecognized option '--quiet'
Usage: adduser [options] LOGIN
       adduser -D
       adduser -D [options]

Options:
  -b, --base-dir BASE_DIR       base directory for the home directory of the
                                new account
  -c, --comment COMMENT         GECOS field of the new account
  -d, --home-dir HOME_DIR       home directory of the new account
  -D, --defaults                print or change default useradd configuration
  -e, --expiredate EXPIRE_DATE  expiration date of the new account
  -f, --inactive INACTIVE       password inactivity period of the new account
  -g, --gid GROUP               name or ID of the primary group of the new
                                account
  -G, --groups GROUPS           list of supplementary groups of the new
                                account
  -h, --help                    display this help message and exit
  -k, --skel SKEL_DIR           use this alternative skeleton directory
  -K, --key KEY=VALUE           override /etc/login.defs defaults
  -l, --no-log-init             do not add the user to the lastlog and
                                faillog databases
  -m, --create-home             create the user's home directory
  -M, --no-create-home          do not create the user's home directory
  -N, --no-user-group           do not create a group with the same name as
                                the user
  -o, --non-unique              allow to create users with duplicate
                                (non-unique) UID
  -p, --password PASSWORD       encrypted password of the new account
  -r, --system                  create a system account
  -R, --root CHROOT_DIR         directory to chroot into
  -s, --shell SHELL             login shell of the new account
  -u, --uid UID                 user ID of the new account
  -U, --user-group              create a group with the same name as the user
  -Z, --selinux-user SEUSER     use a specific SEUSER for the SELinux user mapping

[!] Failed to switch default user in WSL: Command '['cmd', '/C', 'C:\\Windows\\System32\\lxrun.exe', '/setdefaultuser', 'jason']' returned non-zero exit status 4294967295
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "install.py", line 119, in switch_user_back
    subprocess.check_output(['cmd', '/C', lxpath + '\\lxrun.exe', '/setdefaultuser', user])
  File "C:\Users\jdman\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "C:\Users\jdman\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cmd', '/C', 'C:\\Windows\\System32\\lxrun.exe', '/setdefaultuser', 'jason']' returned non-zero exit status 4294967295

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "install.py", line 123, in switch_user_back
    exit(-1)
  File "C:\Users\jdman\AppData\Local\Programs\Python\Python35\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: -1
```

**Comment by RoliSoft** [comment]
This is actually an issue with WSL, since `lxrun` is the one running the `adduser --quiet` command.

One possible workaround for this would be to create a hook script which replaces `adduser` during installation with a wrapper that removes the unsupported `--quiet` argument. That, or it updates `adduser` to one which supports it.

**Comment by thebitstick** [comment]
Why not use CentOS 7?

**Comment by jdmansour** [comment]
@thebitstick I'm trying to run some legacy software I use at work. The programs exist in binary form and run on CentOS 6 (well, Scientific Linux 6 which is the same). On every other OS like Centos 7 or Ubuntu, I would have to do a lot of hacks with LD_LIBRARY_PATH and so on. It would be very complicated to compile everything from scratch.

@RoliSoft It's tricky... the hook script only runs after switching to the new OS, which is too late. I can't run `bash.exe` do do anything with CentOS. I am trying to replace `adduser` during `install.py`, but that is quite hard. `lxrun` doesn't run `adduser` if it is a script, so I have to compile a binary (on another CentOS 6 system). Also, on CentOS, `adduser` is a link to `useradd`, which is a different program on Ubuntu...

**Comment by thebitstick** [comment]
@jdmansour @RoliSoft you could try adding to the install.py something that checks if installing CentOS 6 or other out-of-date distros and change the command from `adduser --quiet` to to `adduser`

**Comment by jdmansour** [comment]
The `adduser` command gets called by `lxrun`, not directly by the installation script. Anyway, I believe this is not the core problem. I can sidestep this issue by using `lxrun /setdefaultuser root` before running the install script. In this case there is no error message, but I still can't enter WSL. `bash.exe` doesn't work, nor does anything like `bash.exe ls`. Strangely enough, `lxrun.exe` can successfully start binaries (like `adduser`, `usermod`, `passwd`) in the CentOS image, but `bash.exe` refuses to do anything, and gives no error message.

**Comment by RoliSoft** [comment]
@jdmansour Writing to files outside of WSL is very tricky indeed. One thing I found that _mostly_ works, is to not create/delete the file, but rather append to it.

Truncation works with some applications, but not with others. I haven't been able to consistently and successfully truncate files and replace their content from outside of WSL yet.

That being said, files like `/etc/passwd` are truncated and overwritten by the installer script, and they seem to work.

It would really save a lot of trouble if Microsoft would release some documentation or expose new APIs to write VoIFs metadata to regular files.

**Comment by udif** [comment]
I'm running into the same problem, for the same reasons (legacy compatibility).
I wounder if this can be bypassed by copying the centos:6.x root under another minimal root and then chroot-ing into the centos:6.x directory?
Yes, this would probably work on 1703/RS2/Creators-Update and forward only.
